### PR TITLE
zephyr: Move Zephyr changes to Zephyr project repo under modules/fatfs/

### PR DESCRIPTION
**Pull request by de-nordic**
The commit removes CmakeLists.txt and modifies zephyr/module.yml to allow storing Zephyr specific sources in module/fatfs directory of Zephyr project.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

TODO:
 - [x] Reduce Zephyr specific modifications to code

2022-11-15: I have decided to provide little override code in ffconf.h inside modules/fs/fatfs, at the end of the file that allows to provide header file with FF_ overrides via command line using preprocessor identifier ZEPHYR_CONFIG_OVERRIDE; this is similar, but not exactly the same, as the LFS_CONFIG works for LittleFS

### CODE REVIEW

**Review by desowin — APPROVED** [review]

**Comment by desowin** [comment]
The `zfs_diskio.c` and `ffconf.h` should be removed from here as these will be in zephyr.

**Comment by de-nordic** [comment]
> The `zfs_diskio.c` and `ffconf.h` should be removed from here as these will be in zephyr.

The zfs_diskio.c has been removed. The ffconf.h has been reverted to original state.

**Comment by de-nordic** [comment]
@Ox11 can you take a look?

**Comment by Ox11** [comment]
Looks good to me. Only question that arises to me is if it is ok, to use the example ffsystem.c from fatfs or if it already should be copied. However, as my pull request will modify this file anyway and therefore be moved to the zephyr space it is not critical from my point of view.

**Comment by de-nordic** [comment]
> ffsystem.c

The ffsystem.c is sample, as the first line explains.
We can have the file in zephyr under any name, that will be pointed by the CMakelists.txt for the module.
You can reimplement the file completely, as it is only important to export proper C definitions to link with the rest of FAT FS code.

**Comment by Ox11** [comment]
Is it possible to contribute to this PR? - May I update the readme?
And can we rename the ffconf.h to ffconf_template.h so we can move this file also to the zephyr repository?

**Comment by de-nordic** [comment]
> Is it possible to contribute to this PR? - May I update the readme? And can we rename the ffconf.h to ffconf_template.h so we can move this file also to the zephyr repository?

I did not move the ffconf.h due to unclear licensing. It is not possible for me to move file, that is not template or skeletal file, out of this repo into Zephyr source tree without adding a license. Till I figure this out the ffconf.h stays where it is.

That is also why the readme stayed as it is.

**Comment by Ox11** [comment]
I see. Then this PR looks good to me. So only a review form someone with permission is missing?

**Review by desowin — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by Ox11** [comment]
As the actual config is now done in the zephyr_fatfs_config.h i would adapt the readme and mention where to find the override config.

**Comment by de-nordic** [comment]
> As the actual config is now done in the zephyr_fatfs_config.h i would adapt the readme and mention where to find the override config.

I will be updating FATFS to 0.15 in next step, so reverting README does not make sense as it will be completely overwritten.

**Pull request merged**
