### PR TITLE
[RFC] fat_fs: Add reentrant zephyr support

### PR DESCRIPTION
**Pull request by Ox11**
fat_fs: Add reentrant zephyr support
This commit adapts the readme as zephyr is now able to configure
the FatFs FF_FS_REENTRANT option and support fs actions from
multiple threads.

Signed-off-by: Nicola Ochsenbein <Nicola.Ochsenbein@husqvarnagroup.com>

### CODE REVIEW

**Comment by Ox11** [comment]
@de-nordic Could you also review this PR?

**Comment by Ox11** [comment]
How should I handle the file-header in the newly created file [zffsystem.c](https://github.com/zephyrproject-rtos/fatfs/blob/b1b84baa887ccd12dfffd17460f307a84d0a9766/option/zffsystem.c)? - It is based on the [ffsystem.c](https://github.com/zephyrproject-rtos/fatfs/blob/b1b84baa887ccd12dfffd17460f307a84d0a9766/option/ffsystem.c) provided by ChaN but copied into a new file to not modify the example file

**Comment by Ox11** [comment]
@de-nordic could you decide what you would prefer?

**Comment by de-nordic** [comment]
> @de-nordic could you decide what you would prefer?

I have started the work, to move Zephyr specific code, here https://github.com/zephyrproject-rtos/fatfs/pull/14. I should have it ready for review Today.

**Comment by Ox11** [comment]
I didn't notice that, sorry. Thanks alot!

**Pull request closed without merging**
